//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class baiViet
    {
        public string maBV { get; set; }
        public string tenBV { get; set; }
        public string hinhDD { get; set; }
        public string ndTomTat { get; set; }
        public Nullable<System.DateTime> ngayDang { get; set; }
        public string loaiTin { get; set; }
        public string noiDungBV { get; set; }
        public string email { get; set; }
        public Nullable<bool> daDuyet { get; set; }
        public Nullable<int> soLanDoc { get; set; }
    
        public virtual loaiTin loaiTin1 { get; set; }
        public virtual quanTri quanTri { get; set; }
    }
}
